import { images } from "../data/images";
import { routes } from "../context/NavContext";
import { ButtonLink } from "../components/Button";
import { PageHero } from "../components/PageHero";
import { QuoteForm } from "../components/QuoteForm";
import { ReplaceableImage } from "../components/ReplaceableImage";
import { Reveal } from "../components/Reveal";

const occasions = [
  { title: "Diwali gifting", body: "The season companies plan for. A hamper that feels festive without being generic." },
  { title: "Employee appreciation", body: "A gift that treats people as more than a headcount — and still arrives on time, at scale." },
  { title: "Corporate festivals", body: "Year-round occasions that deserve more than a catalogue mug." },
  { title: "Team celebrations", body: "Milestones, offsites, closings — a shared table, packed with care." },
  { title: "Client & partner gifting", body: "Something a client will open, eat, and remember as yours — and as theirs." },
];

const capabilities = [
  {
    tag: "Branding",
    title: "Co-Branding & Personalisation",
    body: "Custom outer sleeve with your company logo, leadership greeting card, and bespoke festive messaging included for orders above 50 units.",
  },
  {
    tag: "Logistics",
    title: "Pan-India Multi-Drop Dispatch",
    body: "Choose single-point delivery to your headquarters, or provide a CSV for individual doorstep delivery to remote employees in tier-1, tier-2, and tier-3 cities.",
  },
  {
    tag: "Compliance",
    title: "GST Invoices & Vendor Onboarding",
    body: "Fully compliant corporate billing with valid GST invoices, vendor registration paperwork, MSME alignment, and formal receipts.",
  },
  {
    tag: "Impact",
    title: "Auditable Social Impact",
    body: "Every hamper order comes with a certificate of social contribution detailing the producer community and livelihood impact generated by your purchase.",
  },
];

const steps = [
  { n: "01", title: "Tell us what you need", body: "Quantity, occasion, branding needs, and delivery requirements." },
  { n: "02", title: "Receive a custom quote", body: "Samman confirms availability, volume tiers, and delivery schedule." },
  { n: "03", title: "Approve your order", body: "Finalise quantity, artwork for sleeves, and delivery addresses." },
  { n: "04", title: "Gift with meaning", body: "Hampers reach employees, customers or partners on schedule." },
];

export function Corporate() {
  return (
    <>
      <PageHero eyebrow="Corporate Gifting" title="Made for gifting at scale.">
        <p>
          Samman is designed for companies — HR, CSR, procurement — who need a gift that holds up in a boardroom and in
          a village kitchen. The Signature Hamper is the first offering. Bulk is the intended path.
        </p>
      </PageHero>

      <section className="bg-ivory">
        <div className="mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 sm:px-8 lg:grid-cols-2 lg:gap-16 lg:py-24">
          <Reveal>
            <ReplaceableImage
              src={images.hamperLifestyle}
              alt="Samman hamper on a conference table"
              id="corp-lifestyle"
              className="aspect-[4/3] w-full"
            />
          </Reveal>
          <Reveal delay={80}>
            <p className="eyebrow">The product</p>
            <h2 className="display mt-4 text-3xl sm:text-4xl">Samman Signature Hamper · ₹999</h2>
            <p className="prose-body mt-6">
              ₹999 is the starting reference price. It is not a checkout button. Companies tell us how many, for when,
              and to where. We quote. You approve. Hampers move.
            </p>
            <p className="prose-body mt-4">
              Quantities can be tailored — from a leadership group of 25 to a thousand-person Diwali roster.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <ButtonLink to={routes.quote}>Request a Bulk Quote</ButtonLink>
              <ButtonLink to={routes.hamper} variant="secondary">
                See the Hamper
              </ButtonLink>
            </div>
          </Reveal>
        </div>
      </section>

      {/* Corporate Capabilities & Specifications Module */}
      <section className="border-t border-ink/8 bg-cream">
        <div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24">
          <Reveal>
            <p className="eyebrow">Procurement &amp; Logistics</p>
            <h2 className="display mt-4 text-3xl sm:text-4xl">Built for enterprise procurement.</h2>
            <p className="prose-body mt-4 max-w-2xl">
              We know corporate gifting requires reliability, compliance, and flawless presentation. Here is what we provide for every enterprise partner.
            </p>
          </Reveal>
          <div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {capabilities.map((cap, i) => (
              <Reveal key={cap.title} delay={i * 70}>
                <div className="h-full border border-ink/10 bg-ivory p-7 flex flex-col justify-between shadow-xs">
                  <div>
                    <span className="text-[0.65rem] font-medium tracking-[0.2em] uppercase text-terracotta-dark">
                      {cap.tag}
                    </span>
                    <h3 className="display mt-3 text-2xl">{cap.title}</h3>
                    <p className="mt-4 text-sm font-light leading-relaxed text-ink-soft">{cap.body}</p>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>

          <div className="mt-12 rounded border border-terracotta-dark/20 bg-terracotta-dark/5 p-6 sm:p-8 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <p className="font-serif text-xl text-ink">Minimum Order &amp; Timelines</p>
              <p className="mt-1 text-sm font-light text-muted">
                MOQ: <strong>25 units</strong> · Standard lead time: <strong>10–14 days</strong> · Festive peak (Diwali): <strong>3–4 weeks lead time</strong>.
              </p>
            </div>
            <ButtonLink to={routes.quote} className="shrink-0">
              Check Availability
            </ButtonLink>
          </div>
        </div>
      </section>

      <section className="bg-ivory">
        <div className="mx-auto max-w-7xl px-5 py-20 sm:px-8">
          <Reveal>
            <p className="eyebrow">Occasions</p>
            <h2 className="display mt-4 text-3xl sm:text-4xl">When companies give.</h2>
          </Reveal>
          <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {occasions.map((o, i) => (
              <Reveal key={o.title} delay={i * 60}>
                <article className="border-t border-ink/15 pt-6">
                  <h3 className="display text-2xl">{o.title}</h3>
                  <p className="mt-3 text-sm font-light leading-relaxed text-ink-soft">{o.body}</p>
                </article>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      <section className="bg-cream border-t border-ink/8">
        <div className="mx-auto max-w-7xl px-5 py-20 sm:px-8">
          <Reveal>
            <p className="eyebrow">How corporate ordering works</p>
            <h2 className="display mt-4 text-3xl sm:text-4xl">Four steps. No checkout theatre.</h2>
          </Reveal>
          <ol className="mt-14 grid gap-10 md:grid-cols-2 lg:grid-cols-4">
            {steps.map((s, i) => (
              <Reveal key={s.n} delay={i * 80}>
                <li>
                  <p className="font-serif text-4xl italic text-terracotta-dark">{s.n}</p>
                  <h3 className="display mt-4 text-2xl">{s.title}</h3>
                  <p className="mt-3 text-sm font-light leading-relaxed text-muted">{s.body}</p>
                </li>
              </Reveal>
            ))}
          </ol>
          <Reveal>
            <div className="mt-14">
              <ButtonLink to={routes.quote}>Request a Bulk Quote</ButtonLink>
            </div>
          </Reveal>
        </div>
      </section>

      <section className="bg-ivory border-t border-ink/8">
        <div className="mx-auto max-w-3xl px-5 py-20 sm:px-8">
          <Reveal>
            <p className="eyebrow text-center">Enquiry</p>
            <h2 className="display mt-4 text-center text-3xl sm:text-4xl">Request a corporate quote</h2>
            <p className="prose-body mx-auto mt-4 max-w-lg text-center">
              Share your team size and timeline. We will return with a detailed quotation including co-branding options and volume pricing.
            </p>
            <div className="mt-12">
              <QuoteForm />
            </div>
          </Reveal>
        </div>
      </section>
    </>
  );
}
